AWSTemplateFormatVersion: "2010-09-09"
Description: "Selenium Grid resources"
Parameters:
  CFnTemplateBucketName:
    Type: "String"
  CFnTemplateBucketRegion:
    Type: "String"
  KeyPairName:
    Type: "String"
Mappings:
  Constraints:
    CFt:
      Network: "selenium-grid-on-aws/aws/cft/network.yml"
      SeleniumHub: "selenium-grid-on-aws/aws/cft/selenium-hub.yml"
      SeleniumNode: "selenium-grid-on-aws/aws/cft/selenium-node.yml"
    Network:
      VpcCidrBlock: "192.168.1.0/24"
      PublicSubnetCidrBlock: "192.168.1.0/27"
      PrivateSubnetCidrBlock: "192.168.1.32/27"
Conditions:
  IsUsEast1: !Equals [ !Ref CFnTemplateBucketRegion, "us-east-1" ]
  IsUsEast2: !Equals [ !Ref CFnTemplateBucketRegion, "us-east-2" ]
Resources:
  Network:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3${Region}.amazonaws.com/${CFnTemplateBucketName}/${TemplatePath}"
          - {
              Region: !If [ IsUsEast1, "", !If [ IsUsEast2, ".${AWS::Region}", !Sub "-${AWS::Region}" ]],
              TemplatePath: !FindInMap [ Constraints, CFt, Network ]
            }
      TimeoutInMinutes: "5"
      Parameters:
        ParentStackName: !Ref AWS::StackName
        VpcCidrBlock: !FindInMap [ Constraints, Network, VpcCidrBlock ]
        PublicSubnetCidrBlock: !FindInMap [ Constraints, Network, PublicSubnetCidrBlock ]
        PrivateSubnetCidrBlock: !FindInMap [ Constraints, Network, PrivateSubnetCidrBlock ]
  SeleniumHub:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3${Region}.amazonaws.com/${CFnTemplateBucketName}/${TemplatePath}"
          - {
              Region: !If [ IsUsEast1, "", !If [ IsUsEast2, ".${AWS::Region}", !Sub "-${AWS::Region}" ]],
              TemplatePath: !FindInMap [ Constraints, CFt, SeleniumHub ]
            }
      TimeoutInMinutes: "30"
      Parameters:
        ParentStackName: !Ref AWS::StackName
        VpcId: !GetAtt Network.Outputs.VpcId
        SubnetId: !GetAtt Network.Outputs.PublicSubnetId
        KeyPairName: !Ref KeyPairName
        DefaultSecurityGroupId: !GetAtt Network.Outputs.DefaultSecurityGroupId
  SeleniumNode:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        Fn::Sub:
          - "https://s3${Region}.amazonaws.com/${CFnTemplateBucketName}/${TemplatePath}"
          - {
              Region: !If [ IsUsEast1, "", !If [ IsUsEast2, ".${AWS::Region}", !Sub "-${AWS::Region}" ]],
              TemplatePath: !FindInMap [ Constraints, CFt, SeleniumNode ]
            }
      TimeoutInMinutes: "30"
      Parameters:
        ParentStackName: !Ref AWS::StackName
        VpcId: !GetAtt Network.Outputs.VpcId
        SubnetId: !GetAtt Network.Outputs.PublicSubnetId
        KeyPairName: !Ref KeyPairName
        DefaultSecurityGroupId: !GetAtt Network.Outputs.DefaultSecurityGroupId
        SeleniumHubIP: !GetAtt SeleniumHub.Outputs.SeleniumHubPrivateIp
Outputs:
  SeleniumHubConsole:
    Value: !GetAtt SeleniumHub.Outputs.SeleniumHubConsole
